-- MySQL Script generated by MySQL Workbench
-- 04/10/14 18:26:57
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ourtrips_runner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ourtrips_runner` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ourtrips_runner` ;

-- -----------------------------------------------------
-- Table `ourtrips_runner`.`rangi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`rangi` (
  `id_rangi` INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ranga` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rangi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`uzytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`uzytkownicy` (
  `id_uzytkownika` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `haslo` VARCHAR(45) NOT NULL,
  `data_rejestracji` DATETIME NOT NULL,
  `nr_rangi` INT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Rangi w systemie:' /* comment truncated */ /*1 - użytkownik
2 - moderator
3 - administrator*/,
  `imie` VARCHAR(36) NULL,
  `nazwisko` VARCHAR(45) NULL,
  `waga` TINYINT UNSIGNED NULL,
  `wzrost` TINYINT UNSIGNED NULL,
  `plec` SET('m','k') NULL,
  `miejscowosc` VARCHAR(45) NULL,
  `motto` VARCHAR(245) NULL,
  `ostatnie_logowanie` DATETIME NULL,
  `potwierdzony_mail` BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_uzytkownika`),
  INDEX `nr_rangi_idx` (`nr_rangi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`zadania_resetu_hasla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`zadania_resetu_hasla` (
  `id_zadania` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_uzytkownika` INT UNSIGNED NOT NULL,
  `data_zadania` DATETIME NOT NULL,
  PRIMARY KEY (`id_zadania`),
  INDEX `id_uzytkownika_idx` (`nr_uzytkownika` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`trasy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`trasy` (
  `id_trasy` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_uzytkownika` INT UNSIGNED NULL,
  `dlugosc_trasy` DECIMAL(4,3) UNSIGNED NULL,
  `przebieg_trasy` VARCHAR(245) NULL,
  `data_dodania` DATETIME NOT NULL,
  PRIMARY KEY (`id_trasy`),
  INDEX `nr_uzytkownika_idx` (`nr_uzytkownika` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`wiadomosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`wiadomosci` (
  `id_wiadomosci` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_nadawcy` INT UNSIGNED NOT NULL,
  `nr_adresata` INT UNSIGNED NOT NULL,
  `temat` VARCHAR(45) NULL,
  `tresc` VARCHAR(2000) NULL,
  `data_nadania` DATETIME NOT NULL,
  `data_przeczytania` DATETIME NULL,
  PRIMARY KEY (`id_wiadomosci`),
  INDEX `nr_nadawcy_idx` (`nr_nadawcy` ASC),
  INDEX `nr_odbiorcy_idx` (`nr_adresata` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`sporty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`sporty` (
  `id_sportu` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa_sportu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sportu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`aktywnosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`aktywnosci` (
  `id_aktywnosci` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_sportu` TINYINT UNSIGNED NOT NULL,
  `nr_uzytkownika` INT UNSIGNED NOT NULL,
  `nazwa_treningu` VARCHAR(45) NULL,
  `opis` VARCHAR(45) NULL,
  `tempo` DECIMAL(4,2) NULL,
  `dystans` DECIMAL(6,3) NULL,
  `data_treningu` DATE NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  PRIMARY KEY (`id_aktywnosci`),
  INDEX `nr_uzytkownika_idx` (`nr_uzytkownika` ASC),
  INDEX `nr_sportu_idx` (`nr_sportu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`polubienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`polubienia` (
  `nr_uzytkownika` INT UNSIGNED NOT NULL,
  `nr_aktywnosci` INT UNSIGNED NOT NULL,
  `data_polubienia` DATETIME NOT NULL,
  PRIMARY KEY (`nr_uzytkownika`, `nr_aktywnosci`),
  INDEX `nr_aktywnosci_idx` (`nr_aktywnosci` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`komentarze_do_aktywnosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`komentarze_do_aktywnosci` (
  `id_komentarza` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_aktywnosci` INT UNSIGNED NOT NULL,
  `nr_uzytkownika` INT UNSIGNED NOT NULL,
  `tresc` VARCHAR(245) NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  PRIMARY KEY (`id_komentarza`),
  INDEX `nr_uzytkownika_idx` (`nr_uzytkownika` ASC),
  INDEX `nr_aktywnosci_idx` (`nr_aktywnosci` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`komentarze_do_profilu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`komentarze_do_profilu` (
  `id_komentarza` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_uzytkownika` INT UNSIGNED NOT NULL,
  `nr_profilu` INT UNSIGNED NOT NULL,
  `tresc` VARCHAR(245) NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  PRIMARY KEY (`id_komentarza`),
  INDEX `nr_uzytkownika_idx` (`nr_uzytkownika` ASC),
  INDEX `nr_profilu_idx` (`nr_profilu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`rodzaje_relacji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`rodzaje_relacji` (
  `id_relacji` INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `relacja` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_relacji`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`relacje_uzytkownikow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`relacje_uzytkownikow` (
  `nr_pierwszego` INT UNSIGNED NOT NULL,
  `nr_drugiego` INT UNSIGNED NOT NULL,
  `nr_rodzaju` INT(1) UNSIGNED NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  PRIMARY KEY (`nr_pierwszego`, `nr_drugiego`),
  INDEX `nr_drugiego_idx` (`nr_drugiego` ASC),
  INDEX `nr_relacji_idx` (`nr_rodzaju` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`cele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`cele` (
  `id_celu` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_sportu` TINYINT UNSIGNED NULL,
  `nr_usera` INT UNSIGNED NOT NULL,
  `nazwa_celu` VARCHAR(45) NULL,
  `opis` VARCHAR(45) NULL,
  `data_poczatku` DATE NULL,
  `data_konca` DATE NULL,
  `data_dodania` DATETIME NOT NULL,
  `ilosc_km` DECIMAL(6,3) UNSIGNED NULL,
  PRIMARY KEY (`id_celu`),
  INDEX `nr_usera_idx` (`nr_usera` ASC),
  INDEX `nr_sportu_idx` (`nr_sportu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`rywalizacje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`rywalizacje` (
  `id_rywalizacji` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa_rywalizacji` VARCHAR(45) NOT NULL,
  `opis_rywalizacji` VARCHAR(1445) NULL,
  `nr_sportu` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `data_startu` DATE NOT NULL,
  `data_konca` DATE NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  PRIMARY KEY (`id_rywalizacji`),
  INDEX `nr_sportu_idx` (`nr_sportu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`zgloszenia_do_rywalizacji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`zgloszenia_do_rywalizacji` (
  `nr_rywalizacji` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nr_usera` INT UNSIGNED NOT NULL,
  `data_zapisania` DATETIME NULL,
  PRIMARY KEY (`nr_rywalizacji`, `nr_usera`),
  INDEX `nr_rywalizacji_idx` (`nr_rywalizacji` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ourtrips_runner`.`wspolrzedne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ourtrips_runner`.`wspolrzedne` (
  `nr_usera` INT UNSIGNED NOT NULL,
  `szerokosc` DECIMAL(6,3) NOT NULL,
  `dlugosc` DECIMAL(6,3) NOT NULL,
  `data_ustawienia` DATETIME NOT NULL,
  PRIMARY KEY (`nr_usera`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
